<a href="https://colab.research.google.com/github/lanjudkarrenuka/workshop/blob/main/NUMPY_BASICS_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# np.array
#import numpy as np

#a = np.array([1,2,3])
#print(a)
a= np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
